### ISSUE TITLE
one schedule but multiple events

### ISSUE THREAD

**Issue by hklages** [Steve-Mcl/node-red-contrib-cron-plus#22]
I want to renew a bearer every month. For that I use cron plus with a simple schedule: "0 0 0 15 * *". My expectation is that this will only create one trigger per month. But today I got triggers on 03:49, ..., 16:33, 16:45

What is wrong? 

Could you also help me to understand the  provided information in the screen shot - there are multiple triggers on 14th and schedule is for - (minus) xxxx. 

![cronplus](https://user-images.githubusercontent.com/17273119/90262208-4f736780-de4e-11ea-9a7b-11115c3cc8a9.png)

**Comment by hklages** [comment]
Hardware is [CCU3](https://www.homematic-ip.com/en/products/detail/smart-home-central-control-unit-ccu3.html) based on raspberry pi 3b with specialized operating system (debian type). 

There were about 10 cron-plus nodes - some with multiple schedules.

I did use the recent (at that time when reporting the issue) cron-plus version but had to install it as NodeRED crashes permanently shortly after restart. There were hundreds of messages in the log file - just information. I did delete the log file to clean up everything. After removing all nodes and cron-plus the system started and since then worked fine.

As I can not provide any further information we can close this issue.

**Comment by Steve-Mcl** [comment]
@hklages thanks for the feedback - your issues may have impacted cron plus before i updated it to handle system time changes. Hopefully since the updates (to cron-plus and your system) it will behave.

Let me know if it happens again - I would hate to think this is an issue in the cron-plus node & would appreciate feedback if it happens again.

Cheers, Steve.
