### ISSUE TITLE
"Beginning of the month" cron event went crazy today

### ISSUE THREAD

**Issue by ipatalas** [Steve-Mcl/node-red-contrib-cron-plus#35]
Hi, just had a very strange behavior of this add-on.
I have a flow which triggers a "beginning of the month" event in HA so that I can do stuff based on that (basically reset some counters).
For unknown reason it thinks today is the first day of the month. It started throwing those events like crazy (dozens a second) and almost killed my HA. Luckily my box is under my desk and I was nearby so I heard the fan going crazy.

The options are as follows:
![image](https://user-images.githubusercontent.com/2623329/113064084-a8fa8d80-91b6-11eb-8ac7-4d09e8dc0b16.png)
It says next event is in the past ??
What's even more weird is that I have this flow for like half a year or something and it's been working perfectly so far. Today was the first failure.
Even if I change timezone it still shows incorrect data and thinks today is the first day of the month while it should be tomorrow.

Version of the node: 1.3.0

**Comment by ipatalas** [comment]
When I change cron expression to 2nd day of the month this happens:
![image](https://user-images.githubusercontent.com/2623329/113064497-62f1f980-91b7-11eb-9b1c-f02d27c3ab32.png)
Looks like something is broken in March?

**Comment by Steve-Mcl** [comment]
That is most strange and does not happen on the latest version (not sure if it happened on V1.3.0 either mind)

![so6Dw8Eigc](https://user-images.githubusercontent.com/44235289/113195466-380cb180-925a-11eb-8eb8-cb10defe8caa.gif)


Are you in a position to upgrade to 1.4.3 & try again please?
![image](https://user-images.githubusercontent.com/44235289/113195019-b2890180-9259-11eb-84bf-38d0db857c95.png)

**Comment by ipatalas** [comment]
Did the update but no luck:
![image](https://user-images.githubusercontent.com/2623329/113196586-f84ac780-9263-11eb-9e77-2224dbee5d74.png)
Of course restarted my NR after the update.
Any way to debug those cron expressions?

**Comment by ipatalas** [comment]
Tried using `cronosjs` which is used under the hood and it gives correct result but this is on my desktop. I don't know how to get into node-red HA add-on so that I'm inside the docker container NR is running on.

**Comment by Steve-Mcl** [comment]
Hi @ipatalas 

> If you can give me a hint on how to debug this add-on in browser then I can try debugging and finding where does the problem happen. I do have some JS experience but can't find the file to debug :D 

That would be helpful. the main code runs server side (so browser debug is not the best bet, you'd be better off with VSCode).

I have written up on the forum how to debug a contrib node... 
https://discourse.nodered.org/t/how-to-proper-debug-custom-node/9308/13?u=steve-mcl

that said...
the tooltip text is generated server side but it is parsed client side. If you open `.node-red/node_modules/node-red-contrib-cron-plus/cronplus.html` and find `var debug = false;`, set it to `var debug = true;` & restart node-red.  You will start to see debug messages coming from the client side code in the browsers console (devtools) that will lead you to the client side runtime code. Once you can see and inspect the runtime code in devtools, find this line `url: "cronplus/0/expressionTip"` and put a debug stop here and type into the cron text input - inspect the values coming from server side.  If they look wrong, then the issue is server side.

On server side, the data for the tooltip is generated at around line 1670 (look for `if(operation == "expressionTip"){` - this is a HTTP endpoint (that the client side calls) whenever you type into the cron expression. the typed cron expression is temporarily setup in memory on the server side and its schedules are reported back to the browser to be displayed in the tooltip.

---

Questions on your setup...
1. Is node-red running in a docker image (or HA container)?
1. What version of node-js is this node-red running on? (you can use an exec node to run `node -v` is necessary)
1. What version of node-red are you running?
1. Do you know the timezone set on the OS/container where this node-red is running (if you have no access to a terminal, an exec node running `cat /etc/timezone` or even just `date` should give us a clue
1. Can you please also check the current time on the node-red server (vs your PC / actual time)?
   *   Again, if you cannot get to a terminal, use an exec node and run `date`
1. Can you tell me what timezone and time your client browser is running in also please - might be relevant

I am a bit worried there is a bug so would definitely like your support.

Hopefully, if you can provide the above, I can also duplicate your problem.

Thanks, Steve.

**Comment by ipatalas** [comment]
Ok, let's first address the questions:

1. The configuration is.. complicated: Proxmox -> HassOS -> node-red as HA add-on which basically means NR in a docker container
2. node v14.16.0 and npm v6.14.11
3. 1.2.9 so the latest
4. There is no /etc/timezone (:O) file but `date` says CEST which is my time zone.
5. That was one of the first things I checked - it's all good inside the NR container - perfectly matches my local machine
6. `CEST`

Now the interesting parts begins. I can't find this add-on inside NR container:
![image](https://user-images.githubusercontent.com/2623329/113321162-9c3f7c00-9313-11eb-80d0-4835f904afd9.png)
All the others nodes are there, but this one is missing :(
Tried looking up `cron` but like you can see nothing interesting.

**Comment by ipatalas** [comment]
Ok, so I decided to reinstall the add-on to see if the files will appear so that I can debug and check this:
![image](https://user-images.githubusercontent.com/2623329/113335324-10365000-9325-11eb-819c-d875ed6b0f2e.png)
This is what happens when I leave timezone empty. It's almost good. It now starts on the first day of the month which is good.
Next event in ~29 days which looks fine, but... why is the first item on the list Jun 1st and not May 1st? :O
When I switch cron expression to 2nd day of the month:
![image](https://user-images.githubusercontent.com/2623329/113335714-9d79a480-9325-11eb-8ef9-ed5545c8e4b9.png)
Hahaha, can it get more fun than that? :D

**Comment by ipatalas** [comment]
Ok, for unknown reason this and only this add-on was in `/config/node-red` instead of `/opt/node_modules` like the rest.
Anyway.. figured out it's server side issue when timezone is passed:
![image](https://user-images.githubusercontent.com/2623329/113337712-71abee00-9328-11eb-9902-6dc90877194f.png)
Without the timezone it's ok:
![image](https://user-images.githubusercontent.com/2623329/113337744-7b355600-9328-11eb-9a4c-3698c1e825ee.png)

On my way to figure out how to debug that server side in my configuration - docker container in HassOS VM on a different machine :D

**Comment by ipatalas** [comment]
Ok, so it's not your node:
![image](https://user-images.githubusercontent.com/2623329/113339688-26dfa580-932b-11eb-9552-ead58eb9cb02.png)
It's the `cronosjs` having hard time with timezones?

**Comment by Steve-Mcl** [comment]
Hmmm. That is interesting. Thanks for the feedback. 

Do you intend on raising an issue on the chronosjs repo?  The Dev is very responsive.

**Comment by ipatalas** [comment]
Oh shoot.. it goes even deeper than I initially thought:
![image](https://user-images.githubusercontent.com/2623329/113341341-57284380-932d-11eb-9a43-7ccef3f4a585.png)
Tried that first on my Windows box and also my Debian server.
My windows was node v10, my debian is v12 but when I upgraded my windows to v14 magic happened :D

Yes, I will raise that in their repo. Thanks for assistance :D

**Comment by ipatalas** [comment]
Raised an issue on the original repo - closing this one.

**Comment by jaclarke** [comment]
This bug should now be fixed in cronosjs@1.7.1

**Comment by Steve-Mcl** [comment]
Thanks @ipatalas and @jaclarke  👏👏
